### ISSUE TITLE
Getting an error on player:isHorde ()

### ISSUE THREAD

**Issue by FatGrandpa007** [iThorgrim/lua-account-wide-mount#1]
So I'm using the module, but it won't share the mounts between horde and alliance, and I'm guessing the issue lies in an error I'm getting with it.
Error is following:

`ERROR: ...lua-account-wide-mount-master/lua-account-wide-mount.lua:92: attempt to call method 'isHorde' (a nil value)`

**Comment by KevKalazh** [comment]
Same Problem...

**Comment by FatGrandpa007** [comment]
> Same Problem...

Yeah I sadly haven't found a fix yet either

**Comment by iThorgrim** [comment]
Fixed 👍
